<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Execute Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>512c2d9b-67cb-448e-a579-4d92caf393a5</testSuiteGuid>
   <testCaseLink>
      <guid>eae61749-fe10-459d-a9a8-977b2766c982</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ExcelAPIAutomation/Execute CS_CQS Test</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>fb77e16f-facc-4c0c-a3e2-aba05845d005</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Execute CS_CQS Test</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>fb77e16f-facc-4c0c-a3e2-aba05845d005</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>b9109e85-3e92-40c7-96ed-481e3133b15a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>fb77e16f-facc-4c0c-a3e2-aba05845d005</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>c6a84afc-3a9f-4f5f-a134-f1729fec1d56</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>73dc5d05-5fa2-4802-9dce-eb3ee540814d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ExcelAPIAutomation/Execute CS_CRL Test</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>304fe569-4cd2-4fb0-b8cf-0cdf3c36c680</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Execute CS_CRL Test</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>304fe569-4cd2-4fb0-b8cf-0cdf3c36c680</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>f9f363c2-0bac-4362-ac6b-846497eeb99b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>304fe569-4cd2-4fb0-b8cf-0cdf3c36c680</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>39b4f63d-3968-43be-b0af-bda6dfa0a2d8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>53a4ece8-64f1-40d9-852b-94bc37087e64</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ExcelAPIAutomation/Execute Rec Test</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>ebc154ef-f06c-40da-967f-f65904ca4ddf</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Execute Rec Test</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>ebc154ef-f06c-40da-967f-f65904ca4ddf</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>e55250b6-ed46-40c5-84ce-1ef6937c8722</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ebc154ef-f06c-40da-967f-f65904ca4ddf</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>6d2f8e85-d5e5-4e23-a02d-c19b5140964d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4cc460c0-edae-478f-ad5f-0bd2c35c8b93</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ExcelAPIAutomation/Execute CS_FAS Test</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>56d06208-683a-491a-8721-9fbfeb7682ab</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Execute CS_FAS Test</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>56d06208-683a-491a-8721-9fbfeb7682ab</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>84c4c066-a69b-4174-b395-79c09ec9811a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>56d06208-683a-491a-8721-9fbfeb7682ab</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>ef72cf4c-ee6c-4b0e-984c-4f93503b5899</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
